version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: desafio_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: node_api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=desafio_db
    depends_on:
      - db
    networks:
      - app-network

  jenkins:
    build:
      context: .
      dockerfile: docker/jenkins/Dockerfile
    container_name: jenkins_server
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

volumes:
  db_data:
  jenkins_home:

networks:
  app-network:
    driver: bridge